### ISSUE TITLE
Erro Finalização de Pedido

### ISSUE THREAD

**Issue by awakebrasil** [DripOrg/magento2-payments#1]
Instalação do módulo funcionou corretamente, apenas na hora de finalizar o pedido na página de sucesso recebo o seguinte erro. Versão Magento 2.3.7-p2

Log

Fatal error: Uncaught Error: Call to undefined function Drip\Payments\Utils\get_bloginfo() in XXXX / vendor/drip_app/magento2-payments/Utils/RequestService.php:168

Stack trace: #0 /vendor/drip_app/magento2-payments/Utils/RequestService.php(94):

Drip\Payments\Utils\RequestService->logError('{"url":"v1\\/che...') #1 drip_app/magento2-payments/Observer/AfterPlaceOrder.php(36):

Drip\Payments\Utils\RequestService->createCheckout(Array) #2 /vendor/magento/framework/Event/Invoker/InvokerDefault.php(88):

Drip\Payments\Observer\AfterPlaceOrder->execute(Object(Magento\Framework\Event\Observer)) #3

/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Drip\Payments\Observer\AfterPlaceOrder), Objec in /vendor/drip_app/magento2-payments/Utils/RequestService.php on line 168

Poderia me ajudar, obrigado.

**Comment by ATCamposs** [comment]
O Modulo requestService recebeu uma atualização agora para corrigir esse problema, poderia atualizar sua versão e dizer se o problema foi corrigido ?
os passos para atualização estão aqui: https://github.com/DripOrg/magento2-payments#atualiza%C3%A7%C3%A3o

**Comment by awakebrasil** [comment]
Olá, realizei esse passo já e manteve o problema.

**Comment by ATCamposs** [comment]
é que a função get_bloginfo ja nao existe mais nesse arquivo.. pode me enviar o erro atual ?

**Comment by awakebrasil** [comment]
Manteve, acho que desinstalo e tento instalar de forma manual? fiz por composer 

Fatal error: Uncaught Error: Call to undefined function Drip\Payments\Utils\get_bloginfo

**Comment by ATCamposs** [comment]
faça a reinstalação de forma manual se possível, a remoção via composer ja deve funcionar, só verifique por favor se os arquivos da pasta Drip\Payments serao apagados.

**Comment by awakebrasil** [comment]
Mudou o erro creio que está mais fácil agora 

main.CRITICAL: Client error: `POST https://drip-be.usedrip.com.br/api/v1/merchants/log_plugin_error` resulted in a `401 Unauthorized` response {"report_id":"e051a25533fb178a2b0039d7dbe23373adcaa2ce50b281640d0c6d53eceeb81b","exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 401): Client error: `POST https://drip-be.usedrip.com.br/api/v1/merchants/log_plugin_error` resulted in a `401 Unauthorized` response at /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)"} []

**Comment by ATCamposs** [comment]
o erro 401 indica que a chave que voce está utilizando nao é valida no nosso sistema.
como o link do post é `https://drip-be.usedrip.com.br/`
eu imagino que voce esteja com uma chave de sandbox, mas tentando acessar a produção

**Comment by awakebrasil** [comment]
Mudei a chave e fizemos em sandbox deu tudo certo, somente a imagem do QR que deu erro de resto tudo ok, creio que seja porque está em ambiente de testes, vou testar mais um pouco, de qualquer forma obrigado.

**Comment by ATCamposs** [comment]
Iremos fazer um fix para a imagem do qrCode em sandbox, ela realmente nao está aparecendo, mas o checkout é pago automaticamente depois de cerca de 20 segundos.
